// Courses Class Model and Validations.
// Course Class Structure (id, name, code) and Validations (name and code are required, code must be unique).
// Note: Validation implementation is inside utils/validators.js, and the Course class is defined in this file.

import Validators from "../utils/validators.js";

class Course {
  constructor(id = null, name, code) {
    // ID: auto-generated by json-server (new) or existing ID for (edit)
    if (id) this.id = id;
    this.name = name;
    this.code = code;
  }

  validate() {
    return Validators.validateCourse(this);
  }
}

export default Course;
