// Employee Class Model and Validations (Base Class).
// Employee Class Structure (id, name, email, age, role, position) and Validations (name is required, and email format).
// Note: Validation implementation is inside utils/validators.js, and the Employee class is defined in this file.

import Validators from "../utils/validators.js";
class Employee {
  constructor(id = null, name, email, age, role = "employee", position = null) {
    // ID: auto-generated by json-server (new) or existing ID for (edit)
    if (id) this.id = id;

    this.name = name;
    this.email = email;
    this.age = age;
    this.role = role;

    // Position only for regular employees (not instructors)
    if (position) this.position = position;
  }

  validate() {
    return Validators.validateEmployee(this);
  }
}

export default Employee;
