// Employee Class Model and Validations.
// Employee Class Structure (id, name, email, position) and Validations (name and position are required, and email format).
// Note: Validation implementation is inside utils/validators.js, and the Employee class is defined in this file.

import Validators from "../utils/validators.js";

class Employee {
  constructor(id = null, name, email, position) {
    // ID: auto-generated by json-server (new) or existing ID for (edit)
    if (id) this.id = id;
    this.name = name;
    this.email = email;
    this.position = position;
  }

  validate() {
    return Validators.validateEmployee(this);
  }
}

export default Employee;
