// Instructor Class Model and Validations.
// Instructor Class Structure (id, name, email, department) and Validations (name and department are required, and email format).
// Note: Validation implementation is inside utils/validators.js, and the Instructor class is defined in this file.

import Validators from "../utils/validators.js";

class Instructor {
  constructor(id = null, name, email, department) {
    // ID: auto-generated by json-server (new) or existing ID for (edit)
    if (id) this.id = id;
    this.name = name;
    this.email = email;
    this.department = department;
  }

  validate() {
    return Validators.validateInstructor(this);
  }
}

export default Instructor;
